Update frontend-ci.yml

diff --git a/.github/workflows/frontend-ci.yml b/.github/workflows/frontend-ci.yml
--- a/.github/workflows/frontend-ci.yml
+++ b/.github/workflows/frontend-ci.yml
@@ -10,32 +10,31 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v2
+      - name: Checkout Repository
+        uses: actions/checkout@v2
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: 14
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 14
 
-    - name: Install Dependencies
-      run: |
-        cd frontend
-        npm install
+      - name: Install Dependencies
+        run: |
+          cd frontend_app
+          npm install
 
-    - name: Build
-      run: |
-        cd frontend
-        npm run build
+      - name: Build
+        run: |
+          cd frontend_app
+          npm run build
 
-    - name: Run Tests
-      run: |
-        cd frontend
-        npm test
+      - name: Run Tests
+        run: |
+          cd frontend_app
+          npm test
 
-    - name: Simulate Test Failure
-      run: |
-        cd frontend
-        echo "Test failed!" > test-result.txt
-        exit 1
-      continue-on-error: true
+      - name: Simulate Test Failure
+        run: |
+          echo "Test failed!" > frontend_app/test-result.txt
+          exit 1
+        continue-on-error: true
